# -*- coding: utf-8 -*-
"""Face_Reco.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fs-zdLOeMl1B1AudQeMNhbusxl-c_50T
"""

import cv2
import numpy as np
import time
import random
import datetime
import uuid
from deepface import DeepFace


# ==========================================
# 1. كلاس إدارة هوية السائق عبر DeepFace
# ==========================================
class DriverIdentityManager:
    def __init__(self, estimated_trip_minutes=30):
        self.known_drivers = {}        # مسارات صور السائقين المعتمدين
        self.assigned_driver = None    # السائق المعتمد للرحلة
        self.current_driver = "Unknown"
        self.trip_start_time = time.time()

        # توليد نقطتين عشوائيتين بالثواني (واحدة بالنصف الأول وواحدة بالنصف الثاني)
        total_seconds = estimated_trip_minutes * 60
        half_seconds = total_seconds / 2

        self.random_check_1 = random.uniform(30, max(35, half_seconds))
        self.random_check_2 = random.uniform(half_seconds, max(half_seconds + 5, total_seconds - 30))

        self.check_1_done = False
        self.check_2_done = False

    def register_driver(self, name, image_path):
        """تسجيل السائق المعتمد بحفظ مسار صورته"""
        self.known_drivers[name] = image_path
        print(f"✅ [SYSTEM] Registered driver: {name} (Image: {image_path})")

    def recognize_face(self, frame):
        """التحقق من هوية السائق بمقارنة الفريم مع الصور المسجلة عبر DeepFace"""
        if not self.known_drivers:
            return "No Registered Drivers"

        for name, img_path in self.known_drivers.items():
            try:
                # استخدام نموذج Facenet512 مع كاشف opencv للسرعة
                result = DeepFace.verify(
                    img1_path=frame,
                    img2_path=img_path,
                    model_name="Facenet512",
                    detector_backend="opencv",
                    enforce_detection=False
                )
                if result.get("verified", False):
                    return name
            except Exception as e:
                # في حال تعذر الكشف أو حدوث خطأ أثناء المعالجة
                continue

        return "Unauthorized Driver"

    def audit_check(self, frame, trigger_reason):
        """تنفيذ التحقق وتوثيق المخالفة في حال حدوث تبديل"""
        detected = self.recognize_face(frame)

        # تثبيت هوية السائق عند بداية الرحلة
        if self.assigned_driver is None and detected not in ["No Registered Drivers", "Unauthorized Driver"]:
            self.assigned_driver = detected
            self.current_driver = detected
            print(f"🏁 [TRIP INITIALIZED] Assigned Driver Locked: {self.assigned_driver}")
            return None

        self.current_driver = detected

        # كشف تبديل السائق أو قيادة شخص غير مصرح له
        if detected != self.assigned_driver:
            violation_event = {
                "event_id": f"EV_{str(uuid.uuid4())[:6]}",
                "event_type": "driver_switch_violation",
                "timestamp": datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
                "severity": "high",
                "details": f"Driver Switch Detected at [{trigger_reason}]! Expected: {self.assigned_driver}, Detected: {detected}"
            }
            print(f"\n🚨 [VIOLATION LOGGED] >>> {violation_event}\n")
            return violation_event

        print(f"✔️ [VERIFIED] Identity confirmed at [{trigger_reason}]: {detected}")
        return None

    def update(self, frame, is_in_rest_area=False):
        """التحكم الزمني بنقاط الفحص (البداية، الراحة، العشوائي 1، العشوائي 2)"""
        elapsed = time.time() - self.trip_start_time

        # 1. فحص بداية الرحلة
        if self.assigned_driver is None:
            return self.audit_check(frame, "TRIP_START")

        # 2. فحص منطقة الراحة
        if is_in_rest_area:
            return self.audit_check(frame, "REST_AREA_STOP")

        # 3. الفحص العشوائي الأول
        if not self.check_1_done and elapsed >= self.random_check_1:
            self.check_1_done = True
            return self.audit_check(frame, "RANDOM_CHECK_LEG_1")

        # 4. الفحص العشوائي الثاني
        if not self.check_2_done and elapsed >= self.random_check_2:
            self.check_2_done = True
            return self.audit_check(frame, "RANDOM_CHECK_LEG_2")

        return None


# ==========================================
# 2. تشغيل الكاميرا وتجربة النظام (Standalone Runner)
# ==========================================
def main():
    cap = cv2.VideoCapture(0)

    # إنشاء كائن إدارة الهوية (رحلة مدتها 5 دقائق للتجربة)
    identity_manager = DriverIdentityManager(estimated_trip_minutes=5)

    # تسجيل السائقين المعتمدين (ضع مسار صورة حقيقية واضحة لوجهك)
    identity_manager.register_driver("Abdulrahman", "abdulrahman.jpg")

    print("Face Verification System Started (DeepFace)...")

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        # فحص الحالة آلياً وفق الجدولة الزمنية
        alert = identity_manager.update(frame, is_in_rest_area=False)

        # عرض البيانات الحالية على الشاشة
        cv2.putText(frame, f"Assigned: {identity_manager.assigned_driver}", (30, 40),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)
        cv2.putText(frame, f"Current: {identity_manager.current_driver}", (30, 80),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0, 255, 0), 2)

        if alert:
            cv2.putText(frame, "ALERT: DRIVER SWITCH!", (30, 130),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)

        cv2.imshow("Driver Verification & Audit (DeepFace)", frame)

        # 'q' للخروج، 'r' لمحاكاة دخول منطقة استراحة وفحص السائق
        key = cv2.waitKey(1) & 0xFF
        if key == ord('q'):
            break
        elif key == ord('r'):
            print("Simulating Rest Area Check...")
            identity_manager.update(frame, is_in_rest_area=True)

    cap.release()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    main()